version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    schedule:
      timezone: "05:00 UTC"
      interval: "weekly"
    